LEFT              seek  -5
RIGHT             seek   5
Shift+LEFT        seek -15
Shift+RIGHT       seek  15
Ctrl+LEFT         seek -60
Ctrl+RIGHT        seek  60
=                  cycle video-unscaled
-                  cycle-values window-scale 2 3 1 .5
WHEEL_UP           add volume  5
WHEEL_DOWN         add volume -5
Shift+WHEEL_UP     add volume  20
Shift+WHEEL_DOWN   add volume -20   
Alt+RIGHT          add video-rotate 90
Alt+LEFT           add video-rotate -90
Alt+-              add video-zoom -0.25
Alt+=              add video-zoom 0.25