keep-open=yes
autofit=60%x60%
keepaspect=yes
video-sync=display-resample
profile=high-quality
interpolation=yes
hwdec=auto
volume-max=150
volume=40

[extension.gif]
osc=no
45%x45%
loop-file

[extension.mp3]
autofit=30%x30%

[extension.ogg]
autofit=30%x30%

[extension.wav]
autofit=30%x30%