#          /\
#         /  \
#        /    \
#       /      \    Config By Axell, BTW ❄
#      /   ,,   \
#     /   |  |   \
#    /_-''    ''-_\

#  █   █ ▀ █▄ █ █▀▄ █▀█ █   █   █▀█ █ █ █   ▅▀▀▀▄ █▔▔
#  ▀▃▀▃▀ █ █ ▀█ █▃▀ █▄█ ▀▃▀▃▀   █▀▅ █▅█ █▄▄ ▀▄▂▔  ▂▂█

source = ~/.config/hypr/windowrule/windowfix.conf
source = ~/.config/hypr/windowrule/windowapps.conf
source = ~/.config/hypr/windowrule/windowrule.conf